// All phrases stored in English — translated on-demand to whichever language is selected.
// Translations are cached in memory after first fetch.

export const PHRASE_CATEGORIES = [
  {
    id: 'greetings',
    label: 'Greetings',
    icon: '👋',
    phrases: [
      'Hello!',
      'Good morning!',
      'Good evening!',
      'How are you?',
      'Nice to meet you.',
      'Thank you very much.',
      "You're welcome.",
      'Please.',
      'Excuse me.',
      'I am sorry.',
      'Goodbye!',
      'See you later.',
      'Yes.',
      'No.',
      'I understand.',
      "I don't understand.",
      'Do you speak English?',
      'Please speak more slowly.',
      'Can you repeat that?',
      'My name is Jeff.',
    ],
  },
  {
    id: 'directions',
    label: 'Directions',
    icon: '🗺️',
    phrases: [
      'Where is the restroom?',
      'Where is the nearest train station?',
      'Where is the nearest subway station?',
      'Where is the airport?',
      'Where is the bus stop?',
      'How do I get to the hotel?',
      'Please call a taxi for me.',
      'How far is it from here?',
      'Turn left.',
      'Turn right.',
      'Go straight ahead.',
      'It is on the right side.',
      'It is on the left side.',
      'Is this the correct bus?',
      'Is this the correct train?',
      'I would like to go to this address.',
      'Please show me on the map.',
      'Is it within walking distance?',
      'I am lost.',
      'Can you write it down for me?',
    ],
  },
  {
    id: 'food',
    label: 'Food & Dining',
    icon: '🍜',
    phrases: [
      'A table for two people, please.',
      'The menu, please.',
      'What do you recommend?',
      'I would like to order this.',
      'I am vegetarian.',
      'I am vegan.',
      'I do not eat meat.',
      'I do not eat fish.',
      'I am allergic to peanuts.',
      'I am allergic to shellfish.',
      'I am allergic to gluten.',
      'No spicy food, please.',
      'No sugar, please.',
      'This is delicious!',
      'Water, please.',
      'One more, please.',
      'The check, please.',
      'Can we split the bill?',
      'Do you accept credit cards?',
      'Take-out, please.',
    ],
  },
  {
    id: 'shopping',
    label: 'Shopping',
    icon: '🛍️',
    phrases: [
      'How much does this cost?',
      'That is too expensive.',
      'Can you give me a discount?',
      'Do you have this in another size?',
      'Do you have this in another color?',
      'I will take this one.',
      'Can I try this on?',
      'Where is the fitting room?',
      'Do you accept credit cards?',
      'Do you have a bag?',
      'Can I have a receipt?',
      'I am just looking, thank you.',
      'Do you have anything cheaper?',
      'Is this on sale?',
      'Can you wrap this as a gift?',
      'Do you ship internationally?',
      'I would like to return this.',
      'This is broken.',
      'Do you have this in stock?',
      'Where can I find souvenirs?',
    ],
  },
  {
    id: 'hotel',
    label: 'Hotel & Travel',
    icon: '🏨',
    phrases: [
      'I have a reservation.',
      'My name is Jeff Russell.',
      'What time is check-in?',
      'What time is check-out?',
      'Do you have Wi-Fi?',
      'What is the Wi-Fi password?',
      'Can I have an extra pillow?',
      'Can I have an extra blanket?',
      'My room key does not work.',
      'The air conditioning is not working.',
      'Can you clean my room?',
      'Can you wake me up at 7 AM?',
      'I need help with my bags.',
      'Where is the elevator?',
      'Where is the swimming pool?',
      'Can I have a later checkout?',
      'Is breakfast included?',
      'Where is the nearest ATM?',
      'Can you recommend a nearby restaurant?',
      'I would like to extend my stay.',
    ],
  },
  {
    id: 'emergency',
    label: 'Emergency',
    icon: '🚨',
    phrases: [
      'Help!',
      'Call an ambulance!',
      'Call the police!',
      'Call a doctor!',
      'I need a hospital.',
      'Where is the nearest hospital?',
      'I am sick.',
      'I am injured.',
      'I am having a heart attack.',
      'I cannot breathe.',
      'I am having an allergic reaction.',
      'I am diabetic.',
      'I take this medication.',
      'I have lost my passport.',
      'My wallet was stolen.',
      'My phone was stolen.',
      'I need to contact my embassy.',
      'I need a translator.',
      'Please do not move me.',
      'There is a fire!',
    ],
  },
];

// In-memory translation cache: `phrase|from|to` -> translated string
export const phraseCache = new Map();
